#!/bin/bash

# Root directory for all git repos
gitReposPath=~/git-repos
if ! [[ -f "$gitReposPath" ]]; then
    mkdir -p $gitReposPath
fi

# apt-get packages and install
sudo apt-get update
sudo apt-get --assume-yes install clang cmake emacs gcc git g++ silversearcher-ag tmux

# install tmux-mem-cpu-load (tmcl)
tmclRepoPath=$gitReposPath/tmux-mem-cpu-load
if ! [[ -f "$tmclRepoPath" ]]; then
    mkdir -p $tmclRepoPath
    cd $tmclRepoPath && \
	git clone https://github.com/thewtex/tmux-mem-cpu-load.git . && \
	cmake . && \
	make && \
	sudo make install && \
    cd -
fi

# clone repos from github; these are needed by things like
# .emacs etc.
# Not guarding "git clone" by:
# if ! [[ -f "$repoPath" ]]; then
#    mkdir -p $repoPath
#    git clone ...
# fi
# because new instances will never have these
# even if they do, error lag will catch them
cd $gitReposPath && \
    # https://github.com/aspiers/smooth-scrolling
    git clone https://github.com/aspiers/smooth-scrolling.git && \
    # https://github.com/emacs-helm/helm
    git clone https://github.com/emacs-helm/helm.git && \
    # https://github.com/jwiegley/emacs-async
    git clone https://github.com/jwiegley/emacs-async && \
    # https://github.com/syohex/emacs-helm-ag
    git clone https://github.com/syohex/emacs-helm-ag.git && \
cd -

# install helm
cd ${gitReposPath}/helm
    make
cd -

# download and copy dotfiles to ~/
dotFilesRepoPath=$gitReposPath/dotfiles
if ! [[ -f "$dotFilesRepoPath" ]]; then
    mkdir -p $dotFilesRepoPath
    cd $dotFilesRepoPath && \
	git clone https://github.com/paymaan/dotfiles.git . && \
        # cp and make backup if overwriting
	/bin/cp -fb .* ~/ && \
    cd -
fi

exit 0
