#!/bin/bash

# Variables
callerDir="$(pwd)"
artifactsPath=~/.setup-machine-artifacts
fileStamp="$(date +%Y_%m_%d_at_%{H}hr_%{M}min_%{S}sec)"
logFilePath_stdOut=${artifactsPath}/log_stdout_${fileStamp}.txt
logFilePath_stdErr=${artifactsPath}/log_stderr_${fileStamp}.txt

# Call setup-machine-impl and log output to a file
/bin/bash ${callerDir}/setup-machine-impl \
	  >! $logFilePath_stdOut \
	 2>! $logFilePath_stdErr

# cat error log to stdout
cat $logFilePath_stdErr

exit 0
