#!/bin/bash

githubReposPath=~/code/github-repos

# setup my website and start webserver to host
cd ${githubReposPath}/blog
rm -rf public/
hugo
sudo ufw allow 80
sudo hugo server -p 80 --bind=0.0.0.0 --baseUrl=http://spraza.com
